### ISSUE TITLE
Sampling Site map seems to not find it's KML

### ISSUE THREAD

**Issue by mobb** [sbclter/sbclter-website-2019#15]
After I regenerated the google maps key, this page stopped working:
http://localhost:4000/research/sampling_sites/

It is as if it cannot find the KML files.

**Comment by n-duncan** [comment]
Fixed by moving "sbcMapLayers.yml" back to _data directory
see this commit: https://github.com/sbclter/sbclter-website-2019/commit/0d11e7bfc5c3f86812286affe390280650dbc67d
