### ISSUE TITLE
simple dataset search

### ISSUE THREAD

**Issue by mobb** [sbclter/sbclter-website-2019#16]
a second page dataset page, which does not use the collections.
Similar to this one:
https://ble.lternet.edu/catalog

Default can be all datasets in the repository, with a search box for filtering
(we should talk about what is a good sort order, maybe publication date. 

here is another one:
https://hubbardbrook.org/d/hubbard-brook-data-catalog

we can get ahold of the javascript for either (both) of these.

**Comment by n-duncan** [comment]
Initial version of search page finished
See commit: 1ee55eb7c5becd17a737b9d9568ae14b09b0370a

**Comment by mobb** [comment]
done
