### ISSUE TITLE
Punch list Version 1

### ISSUE THREAD

**Issue by mobb** [sbclter/sbclter-website-2019#29]
Tasks to be completed before you give NCEAS the go-ahead to redirect sbc.lternet to sbclter.msi: 

- [x] `header_nav` has links removed for pages still in draft
- [x] look for errant localhost links (one on home page)
- [x] no comments to Sara or others in any pages
- new image for home page slide show
  - [x] match aspect ratio
  - [x] caption from Sarah
- [x] grep TO DO, NOTE, etc and confirm none
- 3 photos in research section approved or replaced
  - [x]   `research/index.md` composite
  - [x]   `research/theme1/index.md` fishing
  - [x]   `research/theme1/index.md` ammonium-urea-pathways
- [x] `about/collaborators` is complete
- [x] `research/documents/index` done. (maybe: working link for SBC IV)
- [x]  Jim has the apache config set up for internal and external, e.g., for `research/documents`. cert was ordered on Wed. 10/16
- [x] Bob is happy with V1, understands plan and timeline for V2

**Comment by mobb** [comment]
Soon after redirect done:

- [x] confirm links to /external/ work
- [ ] 3rd party link checker
- [x] add a link to /internal/ on data page (?? header nav?? tbd)
- [x] confirm can generate a complete website (to localhost) from a fresh git checkout
- [ ] ask jim for dev space? TBD. localhost may suffice.

**Comment by bmiller-time** [comment]
I'd like to edit the front page.  I'll send you some text.

**Comment by mobb** [comment]
moving the soon-after checklist to its own issue so I can close this one.
