### ISSUE TITLE
data_detail.html: maybe use modules

### ISSUE THREAD

**Issue by mobb** [sbclter/sbclter-website-2019#4]
It might make sense to use modules to divide up the work, use includes to bring them into data_detail.html 
TBD: explain to me if this will work on not

**Comment by lleeoochen** [comment]
Includes only work if we compose our html document on the Jekyll server side. For building html templates on the client side (with JavaScript), the html document won't be too large. However, the JavaScript file will have at least 500 lines. But we can use online tools to minimize the file size (by removing spaces, renaming variables...).

**Comment by mobb** [comment]
will not fix
