### ISSUE TITLE
theme 3, beach images

### ISSUE THREAD

**Issue by mobb** [sbclter/sbclter-website-2019#41]
Jenny sent another beach photo of wrack. consider how to merge this with the beach hopper photo 
See: KelpWrackIVBeach.jpg, beach_hoppers.jpg

**Comment by mobb** [comment]
Jenny's caption for KelpWrackIVBeach.jpt
Caption: The drift kelp exported by nearshore kelp forests is a key subsidy for the food webs of sandy beach ecosystems, fueling high abundance and secondary production of specialized intertidal consumers that serve as shredders of imported kelp wrack.

**Comment by lkuiucsb** [comment]
The KelpWrackIVBeach.jpg figure is now combined with the beach_hoppers.jpg and saved as KelpWrack_comb.jpg
